name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: build-depends
      run: sudo apt update && sudo apt -y install libgtest-dev build-essential cmake libgtest-dev libuv1-dev && sudo apt clean
    - name: configure
      run: mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - name: make
      run: make -j8 -C build/ VERBOSE=1
    - name: make test
      run:  ctest --test-dir build/ --output-on-failure
