name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: build-depends
      run: sudo apt-get -y install libgtest-dev build-essential cmake libgtest-dev libuv1-dev
    - name: configure
      run: mkdir build && cd build && cmake ../
    - name: make
      run: make -C build/ VERBOSE=1
    - name: make test
      run: make -C build/ test VERBOSE=1
